Class {
	#name : 'Card',
	#superclass : 'Object',
	#category : 'IngSoft2-Model',
	#package : 'IngSoft2-Model'
}

{ #category : 'behavior' }
Card >> implementEfectBy: aSpaceship on: aTargetSpaceship in: aGame [
]

{ #category : 'behavior' }
Card >> isInstant [
]

{ #category : 'behavior' }
Card >> isPermanent [
]

{ #category : 'behavior' }
Card >> undoEffect: aGame to: aTargetSpaceship [
]
